fun main() {
    val debitCard = DebitCard(0)
    val creditCard = CreditCard(10000)
    val bonusDebitCard = BonusDebitCard()
    val creditCardCashback = CreditCardCashback()

//    debitCard.pay()
//    debitCard.topUpTheCard()
//    debitCard.getBalanceInfo()
//    debitCard.pay()
//    debitCard.getAvailableFundsInfo()
//    creditCard.getBalanceInfo()
//    creditCard.getAvailableFundsInfo()
//    creditCard.topUpTheCard()
//    creditCard.pay()
//    creditCard.getBalanceInfo()
//    creditCard.getAvailableFundsInfo()
//    creditCard.pay()
//    creditCard.topUpTheCard()
//    creditCard.getBalanceInfo()
//    creditCard.getAvailableFundsInfo()
//    bonusDebitCard.getBalanceInfo()
//    bonusDebitCard.topUpTheCard()
//    bonusDebitCard.pay()
//    bonusDebitCard.getAvailableFundsInfo()
//    bonusDebitCard.pay()
//    bonusDebitCard.getAvailableFundsInfo()
//    bonusDebitCard.pay()
//    bonusDebitCard.getAvailableFundsInfo()
    creditCardCashback.getAvailableFundsInfo()
    creditCardCashback.topUpTheCard()
    creditCardCashback.getAvailableFundsInfo()
    creditCardCashback.pay()
    creditCardCashback.getAvailableFundsInfo()
    creditCardCashback.pay()
    creditCardCashback.getAvailableFundsInfo()
    creditCardCashback.pay()
    creditCardCashback.getAvailableFundsInfo()
    creditCardCashback.getBalanceInfo()

}